---
- hosts: borderleaf2-DC1, borderleaf2-DC2, leaf2-DC1, leaf2-DC2
  gather_facts: no
  tasks:
  - name: Create template
    template:
      src: "~/project/labfiles/AristaTraining/Ansible-Part2/templates/build_even_mlag.j2"
      dest: "~/project/labfiles/AristaTraining/Ansible-Part2/configs/build_even_mlag.cfg"
  - name: Upload config
    eos_config:
      src: "~/project/labfiles/AristaTraining/Ansible-Part2/configs/build_even_mlag.cfg"